name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ['temurin:8', 'temurin:21']
    runs-on: ${{ matrix.os }}
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Dfile.encoding=UTF-8
      JVM_OPTS:  -Dfile.encoding=UTF-8
      ADDITIONAL_JVM_OPTS: -Djava.security.manager=allow
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cache
        uses: coursier/cache-action@v6
      - name: Setup jdk and sbt
        uses: coursier/setup-action@v1
        with:
          jvm: ${{ matrix.java }}
          apps: sbt
      - name: Test
        shell: bash
        run: sbt -v clean test scripted
      - name: Ensure formatting
        shell: bash
        run: sbt -v clean scalafmtSbtCheck scalafmtCheckAll
