name: Release
on:
  push:
    branches:
      - main
    tags: ['*']
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Dfile.encoding=UTF-8
      JVM_OPTS:  -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup cache
        uses: coursier/cache-action@v6
      - name: Setup jdk and sbt
        uses: coursier/setup-action@v1
        with:
          jvm: 'temurin:8'
          apps: sbt
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
